port: 8989
socks-port: 1080
mixed-port: 9090
mode: rule
log-level: info
ipv6: false

dns:
  enable: true
  ipv6: false
  listen: 53
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  enhanced-mode: fake-ip
  fake-ip-range: 100.0.0.1/10 # or 198.18.0.1/16
  nameserver:
    - 8.8.8.8
    - 8.8.4.4
    - https://dns.google/dns-query
    - tls://dns.google:853
    - dhcp://en0
  fallback:
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16

proxies:
                ## Trojan ##

  - name: "ğŸ† Biznet Jakarta"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

  - name: "ğŸ… Biznet Banten"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

  - name: "ğŸ–ï¸ Berkah Solusi"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

  - name: "â˜€ï¸ Qwords"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

  - name: "âš¡ Nusanet"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

  - name: "ğŸŒ¼ Hurricane Electric"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

  - name: "ğŸŒ± Vultr"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

  - name: "ğŸ¥‡ SG.GS"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

  - name: "ğŸªµ M247"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

  - name: "âšª Trojan Unli 1"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

  - name: "âš« Trojan Unli 2"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

  - name: "ğŸŸ¤ Trojan Unli 3"
    type: trojan
    server: server
    port: 443
    password: password
    udp: true
    sni: bug.com
    skip-cert-verify: true

                ## Shadowsocks OBFS ##

  - name: ğŸŒº Argon
    server: login.spotify.com.ovhmelon.kolocokro.xyz
    port: 8090
    type: ss
    cipher: aes-256-gcm
    password: password
    plugin: obfs
    plugin-opts:
      mode: tls
      host: bug.com

  - name: ğŸ’ Raja Mitra
    server: log.spotify.com.m247melon.kolocokro.xyz
    port: 8091
    type: ss
    cipher: aes-256-gcm
    password: PCnnH6SQSnfoS27
    udp : true

  - name: ğŸŒ· Contabo
    server: log.spotify.com.ovhmelon.kolocokro.xyz
    port: 8091
    type: ss
    cipher: aes-256-gcm
    password: PCnnH6SQSnfoS27
    udp : true
    
  - name: ğŸ’® OVH 1
    server: login.spotify.com.ovhmelon.kolocokro.xyz
    port: 8090
    type: ss
    cipher: aes-256-gcm
    password: PCnnH6SQSnfoS27
    udp : true
    
  - name: ğŸµï¸ OVH 2
    server: server
    port: 8443
    type: ss
    cipher: aes-256-gcm
    password: password
    plugin: obfs
    plugin-opts:
      mode: tls
      host: bug.com

                ## Socks5 ##

  - name: "âœ´ï¸ Atha"
    type: socks5
    server: bug.com.server
    port: 443
    username: user
    password: pass
    tls: true
    skip-cert-verify: true
    udp: true

  - name: "ğŸ§¬ Hurricane Electric"
    type: socks5
    server: bug.com.server
    port: 443
    username: user
    password: pass
    tls: true
    skip-cert-verify: true
    udp: true


proxy-groups:
  - name: ğŸ’  Proxy
    type: select
    proxies:
      - ğŸŒ€ Trojan
      - â›‘ï¸ Shadowsocks OBFS
      - ğŸ”— Socks5
      - ğŸŒ  Auto All Proxy
      - ğŸŒŸ Load Balance All Proxy
      - ğŸŒ€ Auto Trojan
      - â›‘ï¸ Auto Shadowsocks OBFS
      - ğŸ”— Auto Socks5
      - ğŸŒ€ Load Balance Trojan
      - â›‘ï¸ Load Balance Shadowsocks OBFS
      - ğŸ”— Load Balance Socks5
      
  - name: ğŸŒ€ Trojan
    type: select
    proxies:
## Trojan
      - ğŸ† Biznet Jakarta
      - ğŸ… Biznet Banten
      - ğŸ–ï¸ Berkah Solusi
      - â˜€ï¸ Qwords
      - âš¡ Nusanet
      - ğŸŒ¼ Hurricane Electric
      - ğŸŒ± Vultr
      - ğŸ¥‡ SG.GS
      - ğŸªµ M247
      - âšª Trojan Unli 1
      - âš« Trojan Unli 2
      - ğŸŸ¤ Trojan Unli 3

  - name: "â›‘ï¸ Shadowsocks OBFS"
    type: select
    proxies:
## Shadowsocks OBFS
      - ğŸŒº Argon
      - ğŸ’ Raja Mitra
      - ğŸŒ· Contabo
      - ğŸ’® OVH 1
      - ğŸµï¸ OVH 2

  - name: "ğŸ”— Socks5"
    type: select
    proxies:
## Socks5
      - âœ´ï¸ Atha
      - ğŸ§¬ Hurricane Electric

  - name: "ğŸŒ  Auto All Proxy"
    type: url-test
    url: 'http://cp.cloudflare.com/'
    interval: 60
    tolerance: 300
    lazy: true
    disable-udp: false
    proxies:
## Trojan
      - ğŸ† Biznet Jakarta
      - ğŸ… Biznet Banten
      - ğŸ–ï¸ Berkah Solusi
      - â˜€ï¸ Qwords
      - âš¡ Nusanet
      - ğŸŒ¼ Hurricane Electric
      - ğŸŒ± Vultr
      - ğŸ¥‡ SG.GS
      - ğŸªµ M247
      - âšª Trojan Unli 1
      - âš« Trojan Unli 2
      - ğŸŸ¤ Trojan Unli 3
## Shadowsocks OBFS
      - ğŸŒº Argon
      - ğŸ’ Raja Mitra
      - ğŸŒ· Contabo
      - ğŸ’® OVH 1
      - ğŸµï¸ OVH 2
## Socks5
      - âœ´ï¸ Atha
      - ğŸ§¬ Hurricane Electric

  - name: "ğŸŒŸ Load Balance All Proxy"
    type: load-balance
    url: 'http://cp.cloudflare.com/'
    interval: 60
    lazy: false
    disable-udp: false
    strategy: consistent-hashing # or round-robin
    proxies:
## Trojan
      - ğŸ† Biznet Jakarta
      - ğŸ… Biznet Banten
      - ğŸ–ï¸ Berkah Solusi
      - â˜€ï¸ Qwords
      - âš¡ Nusanet
      - ğŸŒ¼ Hurricane Electric
      - ğŸŒ± Vultr
      - ğŸ¥‡ SG.GS
      - ğŸªµ M247
      - âšª Trojan Unli 1
      - âš« Trojan Unli 2
      - ğŸŸ¤ Trojan Unli 3
## Shadowsocks OBFS
      - ğŸŒº Argon
      - ğŸ’ Raja Mitra
      - ğŸŒ· Contabo
      - ğŸ’® OVH 1
      - ğŸµï¸ OVH 2
## Socks5
      - âœ´ï¸ Atha
      - ğŸ§¬ Hurricane Electric

  - name: "ğŸŒ€ Auto Trojan"
    type: url-test
    url: 'http://cp.cloudflare.com/'
    interval: 60
    tolerance: 300
    lazy: true
    disable-udp: false
    proxies:
## Trojan
      - ğŸ† Biznet Jakarta
      - ğŸ… Biznet Banten
      - ğŸ–ï¸ Berkah Solusi
      - â˜€ï¸ Qwords
      - âš¡ Nusanet
      - ğŸŒ¼ Hurricane Electric
      - ğŸŒ± Vultr
      - ğŸ¥‡ SG.GS
      - ğŸªµ M247
      - âšª Trojan Unli 1
      - âš« Trojan Unli 2
      - ğŸŸ¤ Trojan Unli 3

  - name: "â›‘ï¸ Auto Shadowsocks OBFS"
    type: url-test
    url: 'http://cp.cloudflare.com/'
    interval: 60
    tolerance: 300
    lazy: true
    disable-udp: false
    proxies:
## Shadowsocks OBFS
      - ğŸŒº Argon
      - ğŸ’ Raja Mitra
      - ğŸŒ· Contabo
      - ğŸ’® OVH 1
      - ğŸµï¸ OVH 2

  - name: "ğŸ”— Auto Socks5"
    type: url-test
    url: 'http://cp.cloudflare.com/'
    interval: 60
    tolerance: 300
    lazy: true
    disable-udp: false
    proxies:
## Socks5
      - âœ´ï¸ Atha
      - ğŸ§¬ Hurricane Electric

  - name: "ğŸŒ€ Load Balance Trojan"
    type: load-balance
    url: 'http://cp.cloudflare.com/'
    interval: 60
    lazy: false
    disable-udp: false
    strategy: consistent-hashing # or round-robin
    proxies:
## Trojan
      - ğŸ† Biznet Jakarta
      - ğŸ… Biznet Banten
      - ğŸ–ï¸ Berkah Solusi
      - â˜€ï¸ Qwords
      - âš¡ Nusanet
      - ğŸŒ¼ Hurricane Electric
      - ğŸŒ± Vultr
      - ğŸ¥‡ SG.GS
      - ğŸªµ M247
      - âšª Trojan Unli 1
      - âš« Trojan Unli 2
      - ğŸŸ¤ Trojan Unli 3

  - name: "â›‘ï¸ Load Balance Shadowsocks OBFS"
    type: load-balance
    url: 'http://cp.cloudflare.com/'
    interval: 60
    lazy: false
    disable-udp: false
    strategy: consistent-hashing # or round-robin
    proxies:
## Shadowsocks OBFS
      - ğŸŒº Argon
      - ğŸ’ Raja Mitra
      - ğŸŒ· Contabo
      - ğŸ’® OVH 1
      - ğŸµï¸ OVH 2

  - name: "ğŸ”— Load Balance Socks5"
    type: load-balance
    url: 'http://cp.cloudflare.com/'
    interval: 60
    lazy: false
    disable-udp: false
    strategy: consistent-hashing # or round-robin
    proxies:
## Socks5
      - âœ´ï¸ Atha
      - ğŸ§¬ Hurricane Electric

rule-providers:
  streaming:
    type: http
    behavior: classical
    path: /streaming.yaml
    url: https://raw.githubusercontent.com/gengkapakzxc/Config-Clashku/main/streaming.yaml

  sosmed:
    type: http
    behavior: classical
    path: /sosmed.yaml
    url: https://raw.githubusercontent.com/gengkapakzxc/Config-Clashku/main/sosmed.yaml
    
  rule_tiktok:
    type: http
    behavior: domain
    path: /rule_tiktok.yaml
    url: https://raw.githubusercontent.com/gengkapakzxc/Config-Clashku/main/rule_tiktok.yaml

rules:
  - RULE-SET,streaming,DIRECT
  - RULE-SET,sosmed,DIRECT
  - RULE-SET,rule_tiktok,DIRECT
  - MATCH,ğŸ’  Proxy




## Trojan
      #- ğŸ† Biznet Jakarta
      #- ğŸ… Biznet Banten
      #- ğŸ–ï¸ Berkah Solusi
      #- â˜€ï¸ Qwords
      #- âš¡ Nusanet
      #- ğŸŒ¼ Hurricane Electric
      #- ğŸŒ± Vultr
      #- ğŸ¥‡ SG.GS
      #- ğŸªµ M247
      #- âšª Trojan Unli 1
      #- âš« Trojan Unli 2
      #- ğŸŸ¤ Trojan Unli 3
## Shadowsocks OBFS
      #- ğŸŒº Argon
      #- ğŸ’ Raja Mitra
      #- ğŸŒ· Contabo
      #- ğŸ’® OVH 1
      #- ğŸµï¸ OVH 2
## Socks5
      #- âœ´ï¸ Atha
      #- ğŸ§¬ Hurricane Electric
